language: ruby

sudo: false

install: ruby -S bundle install --without release development

rvm:
  - 1.9
  - 2.5
  - ruby-head
  - jruby-9.1
  - jruby-9.2

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head

env:
  global:
    - CI="travis"
    - JRUBY_OPTS="--server -J-Xms512m -J-Xmx1024m"

notifications:
  email: false


